export const XBOX_CONTROLLER_BUTTONS = {
    A: 'A',
    B: 'B',
    X: 'X',
    Y: 'Y',
    LEFT_STICK_UP: 'LEFT_STICK_UP',
    LEFT_STICK_DOWN: 'LEFT_STICK_DOWN',
    LEFT_STICK_LEFT: 'LEFT_STICK_LEFT',
    LEFT_STICK_RIGHT: 'LEFT_STICK_RIGHT'
};
